### PR TITLE
 Added Jones as contributor and added 2 posts. 

### PR DESCRIPTION
**Pull request by zachjonesnoel**
*Issue #, if available:*
NA
*Description of changes:*
Added Jones Zachariah Noel as Contributor
Added 2 posts - 
Amplify your web hosting
Understanding AWS Amplify

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by zachjonesnoel** [comment]
Added a new post committed on Aug 24th. So the same PR will be inclusive of that?

**Comment by zachjonesnoel** [comment]
Hi reviewers. Any updated on this PR?

**Comment by aspittel** [comment]
Hey @zachjonesnoel , sorry for the slow response on this - the project is no longer being maintained but will be replaced with something new soon. Thank you so much for writing about amplify and being a member of the community!

**Comment by zachjonesnoel** [comment]
Would be happy to contribute for the new one. 😄 Thanks @aspittel

**Pull request closed without merging**
